version: "3.10"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      # only to be used in development - https://www.youtube.com/watch?v=9uweLP9FV10 10:35 https://www.youtube.com/watch?v=mScd-Pc_pX0 18:30
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    restart: always
    depends_on:
      - db
    networks: 
      - trip-planner-backend

  db:
    image: kartoza/postgis:13
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DBNAME=${DB_NAME}
    restart: always
    networks:
      - trip-planner-backend

networks:
  trip-planner-backend:
    driver: bridge

volumes:
  postgres_data: