# Generated by Django 3.2.5 on 2021-07-29 23:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='This is the title of your trip.', max_length=100, verbose_name='Trip title')),
                ('start_date', models.DateField(help_text='This is the start date of your trip.', verbose_name='Trip start date')),
                ('end_date', models.DateField(help_text='This is the end date of your trip.', verbose_name='Trip end date')),
                ('notes', models.TextField(default='', help_text='These are your notes regarding the trip.', verbose_name='Trip notes')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TripDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(help_text='This is a date within the trip.', verbose_name='date')),
                ('notes', models.TextField(default='', help_text='These are your notes for the day of the trip.', verbose_name='Day notes')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trips.trip')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
